INSERT OR REPLACE INTO Colors
		(Type,										Color)
VALUES	("COLOR_PLAYER_SUK_KHOSROW_I_PRIMARY",		"93,105,70,255"),   --#5D6946
		("COLOR_PLAYER_SUK_KHOSROW_I_SECONDARY",	"224,193,121,255");	--#E0C179

UPDATE PlayerColors
SET     Alt1PrimaryColor = "COLOR_CVS_SASSANID_B_PRIMARY",
        Alt1SecondaryColor = "COLOR_PLAYER_SUK_KHOSROW_I_SECONDARY",
        Alt2PrimaryColor = "COLOR_PLAYER_SUK_KHOSROW_I_SECONDARY",
        Alt2SecondaryColor = "COLOR_PLAYER_SUK_KHOSROW_I_PRIMARY",
        Alt3PrimaryColor = "COLOR_PLAYER_SUK_KHOSROW_I_PRIMARY",
        Alt3SecondaryColor = "COLOR_CVS_SASSANID_A_SECONDARY"
WHERE  Type = 'LEADER_SUK_KHOSROW_I'
AND    Usage = 'Unique';